### ISSUE TITLE
Abnormal results of embedding

### ISSUE THREAD

**Issue by gangwu001** [benedekrozemberczki/Splitter#3]
When i run this model in different datasets (e.g blogcatalog), Some of the dimensions of the vector are greater than or less than negative 1, for example, (1.0,-7.087762355804443,-26.554523468017578,4.721840858459473, ...)

[blogcatalog.zip](https://github.com/benedekrozemberczki/Splitter/files/3337779/blogcatalog.zip)

**Comment by benedekrozemberczki** [comment]
Hi there, could you try out the new version?
