### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by anjalibhavan** [benedekrozemberczki/Splitter#4]
I'm getting this error while running your code:
 
```
File "C:\Users\ANJALI\environments\splitter\src\splitter.py", line 41, in <listcomp>
persona_embedding = np.array([base_node_embedding[original_node] for node, original_node in mapping.items()])
IndexError: index 599 is out of bounds for axis 0 with size 599
```

The number of nodes in my graph are 599. What is the cause for this error?

**Comment by benedekrozemberczki** [comment]
Did you reindex your nodes?

**Comment by anjalibhavan** [comment]
I did not do anything.

**Comment by benedekrozemberczki** [comment]
The question is: Are your nodes indexed consecutively starting from zero?
(see readme)

**Comment by benedekrozemberczki** [comment]
Can I close the issue? :)

**Comment by anjalibhavan** [comment]
The nodes are indexed consecutively but appear in random fashion in my edge list. This is how the edge list starts:
322 234
12 45
...
and so on. Should these be ordered?

**Comment by benedekrozemberczki** [comment]
No. Can you send me the edge list in the format required?

**Comment by anjalibhavan** [comment]
In the csv format?

es1 | es2
-- | --
342 | 233
342 | 30
342 | 189
342 | 458
342 | 297
342 | 20
342 | 158
342 | 133
311 | 256
303 | 373
256 | 311
373 | 303
439 | 435
439 | 247
435 | 439
435 | 247
435 | 272

**Comment by benedekrozemberczki** [comment]
With the separating comma yes. Can you send it to my e-mail?

**Comment by anjalibhavan** [comment]
Okay.

**Comment by alirezabayatmk** [comment]
I'm getting the same error.
```
Traceback (most recent call last):
  File "/home/shady/Projects/GML/SPLITTER/Splitter/src/main.py", line 24, in <module>
    main()
  File "/home/shady/Projects/GML/SPLITTER/Splitter/src/main.py", line 19, in main
    trainer.fit()
  File "/home/shady/Projects/GML/SPLITTER/Splitter/src/splitter.py", line 229, in fit
    self.setup_model()
  File "/home/shady/Projects/GML/SPLITTER/Splitter/src/splitter.py", line 159, in setup_model
    self.egonet_splitter.personality_map)
  File "/home/shady/Projects/GML/SPLITTER/Splitter/src/splitter.py", line 52, in initialize_weights
    persona_embedding = np.array([base_node_embedding[n] for _, n in mapping.items()])
  File "/home/shady/Projects/GML/SPLITTER/Splitter/src/splitter.py", line 52, in <listcomp>
    persona_embedding = np.array([base_node_embedding[n] for _, n in mapping.items()])
IndexError: index 8637 is out of bounds for axis 0 with size 8637
```

The dataset is sorted and also IDs start from zero with no index and header. Also, it just happens on the CA-HepTh dataset and not others which is strange.
