### ISSUE TITLE
AttributeError: module 'networkx' has no attribute 'selfloop_edges'

### ISSUE THREAD

**Issue by chunyuma** [benedekrozemberczki/Splitter#5]
Hello, I followed the instruction to install all the required python packages but when I ran 'python3 src/main.py', I got the following error. Could you please let me know how I can fix it? Thank you!

Traceback (most recent call last):
  File "src/main.py", line 24, in <module>
    main()
  File "src/main.py", line 17, in main
    graph = graph_reader(args.edge_path)
  File "/Users/machunyu/KoslickiLab/Splitter/src/utils.py", line 26, in graph_reader
    graph.remove_edges_from(nx.selfloop_edges(graph))
AttributeError: module 'networkx' has no attribute 'selfloop_edges'

**Comment by zycheng643** [comment]
> Hello, I followed the instruction to install all the required python packages but when I ran 'python3 src/main.py', I got the following error. Could you please let me know how I can fix it? Thank you!
> 
> Traceback (most recent call last):
> File "src/main.py", line 24, in
> main()
> File "src/main.py", line 17, in main
> graph = graph_reader(args.edge_path)
> File "/Users/machunyu/KoslickiLab/Splitter/src/utils.py", line 26, in graph_reader
> graph.remove_edges_from(nx.selfloop_edges(graph))
> AttributeError: module 'networkx' has no attribute 'selfloop_edges'

Have you solved it? Got the same problem

**Comment by PhSe-coder** [comment]
download the _networkx_ package in version 2.4
