### ISSUE TITLE
`community` module not found

### ISSUE THREAD

**Issue by RemyLau** [benedekrozemberczki/Splitter#6]
Hi, I'm trying to test the splitter embedding and encountered this issue of not being able to find the `community` module, which is being imported in `ego_splittying.py`. And I think I've installed all the required packages.

https://github.com/benedekrozemberczki/Splitter/blob/b5b330f90cd585614aa221c608d6fbc4d9a2a7fe/src/ego_splitting.py#L3

**Comment by benedekrozemberczki** [comment]
You need this library:

https://python-louvain.readthedocs.io/en/latest/
